---
- name: "roles/git/tasks/main git global"
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
   - name: user.name
     value: isucon
   - name: user.email
     value: isucon@isucon.com
