---
- name: "role/discocat/tasks/main Existing go version"
  command: "{{ go_path }} version"
  register: go_version_out
  ignore_errors: no
  check_mode: no
  changed_when: no

- name: "role/discocat/tasks/main Result go version"
  debug:
    msg: "{{ go_version_out.stdout }}"

- name: "role/discocat/tasks/main Existing discocat"
  command: "/home/{{ ansible_user }}/go/bin/discocat --version"
  register: go_version_out
  ignore_errors: yes
  check_mode: no
  changed_when: no

- name: "role/discocat/tasks/main Install discocat"
  command: "go install {{ discocat.url }}@{{ discocat.version }}"
  changed_when: no

- name: "role/discocat/tasks/main Check discocat version"
  command: "/home/{{ ansible_user }}/go/bin/discocat --version"
  register: discocat_version_out
  ignore_errors: yes
  check_mode: no
  changed_when: no

- name: "role/discocat/tasks/main Result discocat version"
  debug:
    msg: "{{ discocat_version_out.stdout }}"

- name: "roles/alp/tasks/main Create discocat config dir"
  file:
    path: "/home/{{ ansible_user }}/.config"
    state: directory

- name: "role/discocat/tasks/main Put discocat.yml"
  template:
    src: templates/discocat.yml.j2
    dest: "/home/{{ ansible_user }}/.config/discocat.yml"
