---
- name: "roles/apt-task/tasks/main Add apt repo"
  apt_repository:
    repo: "{{ item }}"
  when: ansible_os_family == "Debian"
  become: yes
  with_items:
    - ppa:fish-shell/release-3
  notify:
    - "apt-update"

- name: "roles/apt-task/tasks/main Add GitHub CLI gpg key"
  shell: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg --yes
  become: yes

- name: "roles/apt-task/tasks/main Set up the stable repository for GitHub CLI"
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  become: yes

- name: "roles/apt-task/tasks/main Install packages with apt"
  apt:
    pkg:
      - git
      - unzip
      - dstat
      - fish
      - percona-toolkit
      - gh
  when: ansible_os_family == "Debian"
  become: yes
